#!/usr/bin/perl

use POSIX qw(strftime);

# Get the time at which the system was started.
$up_time = `cat /proc/uptime | awk '{print $1}';`;
$boot_time = time() - $up_time;
chomp $boot_time;

# Loop through the lines to process from stdin.
while (<>) {
   $line = $_;
   chomp $line;
   if ($line =~ /^\[([\s\d\.]+)\]/) {
      $time_offset = $1;
   }
   $real_time = $boot_time + $time_offset;
   $decimals = sprintf("%05d", ($real_time - int($real_time)) * 100000);
   $real_time = strftime "%d-%m-%Y %H:%M:%S", localtime($real_time);
   $line =~ s/\[[\s\d\.]+\]/\[$real_time\.$decimals\]/;
   print "$line\n";
}

